import { Noto_Sans_Bengali } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";



const notoSansBengali = Noto_Sans_Bengali({
  variable: "--font-noto-bengali",
  subsets: ["bengali"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
    data-theme="light"
      lang="en"
      className={`${notoSansBengali.variable} h-full antialiased`}
    >
      <body className={`${notoSansBengali.className} min-h-full flex flex-col`}>
        <Header />
        {children}
        
        </body>
    </html>
  );
}
